### ISSUE TITLE
cross compile on aix fails

### ISSUE THREAD

**Issue by serak** [elastic/go-sysinfo#106]
env
GOOS=aix
GOARCH=ppc64

`# github.com/elastic/go-sysinfo/providers/aix
..\..\..\..\go\pkg\mod\github.com\elastic\go-sysinfo@v1.7.1\providers\aix\os_aix.go:36:23: undefined: getKernelVersion
..\..\..\..\go\pkg\mod\github.com\elastic\go-sysinfo@v1.7.1\providers\aix\os_aix.go:42:19: cannot assign error to err in multiple assignment

**Comment by serak** [comment]
#107

**Comment by andrewkroh** [comment]
I think the problem here is that os_aix.go depends on a cgo function, but it does not guard itself proper cgo build tags. 

To quote https://go-proverbs.github.io/:

> Cgo must always be guarded with build tags.

So I don't think the solution in #107 is correct for this situation. I think the correct solution is to ensure that cgo is required when when building for aix/ppc64. If cgo is not present then the provider will not be registered.
